format = """
[╭─](fg:#3b4261)\
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$rust\
$golang\
$fill\
$cmd_duration\
$time\
$line_break\
[╰─](fg:#3b4261)\
$character"""

[fill]
symbol = " "

[directory]
style = "bold fg:#7aa2f7"
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "
read_only = " 󰌾"

[git_branch]
symbol = " "
style = "fg:#bb9af7"
format = "on [$symbol$branch(:$remote_branch)]($style) "

[git_status]
style = "fg:#e0af68"
format = '([$all_status$ahead_behind]($style) )'
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
modified = "!${count}"
untracked = "?${count}"
staged = "+${count}"
deleted = "✘${count}"

[character]
success_symbol = "[❯](bold fg:#9ece6a)"
error_symbol = "[❯](bold fg:#f7768e)"
vimcmd_symbol = "[❮](bold fg:#bb9af7)"

[cmd_duration]
min_time = 2000
style = "fg:#e0af68"
format = "took [$duration]($style) "

[time]
disabled = false
style = "fg:#565f89"
format = "[$time]($style)"
time_format = "%H:%M"

[python]
symbol = " "
style = "fg:#e0af68"
format = "[$symbol($version) ]($style)"

[nodejs]
symbol = " "
style = "fg:#9ece6a"
format = "[$symbol($version) ]($style)"

[rust]
symbol = " "
style = "fg:#f7768e"
format = "[$symbol($version) ]($style)"

[golang]
symbol = " "
style = "fg:#7dcfff"
format = "[$symbol($version) ]($style)"
